[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[context.production.environment]
  RANDOM_ENV_VARIABLE = "hello_world"

[context.deploy-preview]
  command = "echo 'deploy preview'"
