[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  package = "@netlify/plugin-a11y"

[context.production.environment]
  RANDOM_ENV_VARIABLE = "hello_world"

[context.deploy-preview.environment]
  RANDOM_ENV_VARIABLE = "something"
