[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[context.production]
  environment = { NETLIFY_VERBOSE = "true" }

[context.deploy-preview]
  environment = { NETLIFY_VERBOSE = "false" }
